#ifndef BINDINGS_H
#define BINDINGS_H
// typesystem_qt
// #include <QtCore>/QDebug>
#include <QtNetwork/QHstsPolicy>

#include "libQuotient/lib/logging.h"
#include "libQuotient/lib/util.h"

// jobs/typesystem_basejob
#include "libQuotient/lib/jobs/basejob.h"
// jobs/typesystem_requestdata
#include "libQuotient/lib/jobs/requestdata.h"

// typesystem_avatar
// #include "libQuotient/lib/avatar.h"
// typesystem_connectiondata
#include "libQuotient/lib/connectiondata.h"
// typesystem_networkaccessmanager
#include "libQuotient/lib/networkaccessmanager.h"

// /*
//  * This part is autogenerated and is replaced on each API update,
//  * do not edit it manually!
//  */
// /* CSAPI */
#include "libQuotient/lib/csapi/third_party_membership.h"
#include "libQuotient/lib/csapi/appservice_room_directory.h"
#include "libQuotient/lib/csapi/search.h"
#include "libQuotient/lib/csapi/logout.h"
#include "libQuotient/lib/csapi/leaving.h"
#include "libQuotient/lib/csapi/admin.h"
#include "libQuotient/lib/csapi/room_send.h"
#include "libQuotient/lib/csapi/read_markers.h"
#include "libQuotient/lib/csapi/tags.h"
#include "libQuotient/lib/csapi/create_room.h"
#include "libQuotient/lib/csapi/sso_login_redirect.h"
#include "libQuotient/lib/csapi/notifications.h"
#include "libQuotient/lib/csapi/typing.h"
#include "libQuotient/lib/csapi/message_pagination.h"
#include "libQuotient/lib/csapi/cross_signing.h"
#include "libQuotient/lib/csapi/voip.h"
#include "libQuotient/lib/csapi/capabilities.h"
#include "libQuotient/lib/csapi/pusher.h"
#include "libQuotient/lib/csapi/keys.h"
#include "libQuotient/lib/csapi/whoami.h"
#include "libQuotient/lib/csapi/list_joined_rooms.h"
#include "libQuotient/lib/csapi/receipts.h"
#include "libQuotient/lib/csapi/device_management.h"
#include "libQuotient/lib/csapi/joining.h"
#include "libQuotient/lib/csapi/third_party_lookup.h"
#include "libQuotient/lib/csapi/banning.h"
#include "libQuotient/lib/csapi/filter.h"
#include "libQuotient/lib/csapi/to_device.h"
#include "libQuotient/lib/csapi/profile.h"
#include "libQuotient/lib/csapi/directory.h"
#include "libQuotient/lib/csapi/versions.h"
#include "libQuotient/lib/csapi/room_upgrades.h"
#include "libQuotient/lib/csapi/inviting.h"
#include "libQuotient/lib/csapi/redaction.h"
#include "libQuotient/lib/csapi/pushrules.h"
#include "libQuotient/lib/csapi/account-data.h"
#include "libQuotient/lib/csapi/wellknown.h"
#include "libQuotient/lib/csapi/administrative_contact.h"
#include "libQuotient/lib/csapi/content-repo.h"
#include "libQuotient/lib/csapi/event_context.h"
#include "libQuotient/lib/csapi/room_state.h"
#include "libQuotient/lib/csapi/kicking.h"
#include "libQuotient/lib/csapi/presence.h"
#include "libQuotient/lib/csapi/report_content.h"
#include "libQuotient/lib/csapi/users.h"
#include "libQuotient/lib/csapi/list_public_rooms.h"
#include "libQuotient/lib/csapi/rooms.h"
#include "libQuotient/lib/csapi/login.h"
#include "libQuotient/lib/csapi/registration.h"
#include "libQuotient/lib/csapi/knocking.h"
#include "libQuotient/lib/csapi/openid.h"
#include "libQuotient/lib/csapi/peeking_events.h"
#include "libQuotient/lib/csapi/definitions/event_filter.h"
#include "libQuotient/lib/csapi/definitions/request_token_response.h"
#include "libQuotient/lib/csapi/definitions/push_ruleset.h"
#include "libQuotient/lib/csapi/definitions/push_rule.h"
#include "libQuotient/lib/csapi/definitions/third_party_signed.h"
#include "libQuotient/lib/csapi/definitions/room_event_filter.h"
#include "libQuotient/lib/csapi/definitions/cross_signing_key.h"
#include "libQuotient/lib/csapi/definitions/sync_filter.h"
#include "libQuotient/lib/csapi/definitions/push_condition.h"
#include "libQuotient/lib/csapi/definitions/request_msisdn_validation.h"
#include "libQuotient/lib/csapi/definitions/openid_token.h"
#include "libQuotient/lib/csapi/definitions/public_rooms_response.h"
#include "libQuotient/lib/csapi/definitions/request_email_validation.h"
#include "libQuotient/lib/csapi/definitions/auth_data.h"
#include "libQuotient/lib/csapi/definitions/client_device.h"
#include "libQuotient/lib/csapi/definitions/device_keys.h"
#include "libQuotient/lib/csapi/definitions/user_identifier.h"
#include "libQuotient/lib/csapi/definitions/wellknown/full.h"
#include "libQuotient/lib/csapi/definitions/wellknown/homeserver.h"
#include "libQuotient/lib/csapi/definitions/wellknown/identity_server.h"
/* CSAPI end */
/* End of autogenerated part */
#endif // BINDINGS_H
